### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by kirbyfan64** [kobalicek/asmjit#10]
I was looking through the docs and noticed some issues. For example, on the page for X86X64Compiler, I found the following issues:

- It says to use the free method of the MemoryManager object returned by getGlobal, when in fact it should be the release method.
- Wherever FuncBuilder is supposed to be used, it says BuildFunction.

In addition, the class JitRuntime is missing. In addition, there are probably more issues that I haven't noticed.

**Comment by kobalicek** [comment]
I'm closing this for now, reopen if there are other documentation issues that I have missed.
