### ISSUE TITLE
wrong emit:mov(bx,123),the prefix was lost

### ISSUE THREAD

**Issue by bughoho** [kobalicek/asmjit#105]
```c++
asmjit::X86Assembler a;
...
a.mov(bx,0x1234)
a.make();
```

the result is:
BB 34 12 => mov ebx,0xXXXX1234

The correct results should be:
66:BB 34 12 => mov bx,0x1234

The prefix instruction was lost.

**Comment by kobalicek** [comment]
Fixed, thanks!
