### ISSUE TITLE
vmovntdq not encoded properly when used with ymm registers

### ISSUE THREAD

**Issue by ireyon** [kobalicek/asmjit#107]
The vmovntq instruction always generates the binary for the XMM version, even when using an YMM register as source:
```
vmovntdq [rax], xmm0                ; C5F9E700   // correct
vmovntdq [rax], ymm0                ; C5F9E700   // should be C5FDE700
```

All other move instructions, including vmovntps and vmovntpd, work fine according to my tests.

**Comment by kobalicek** [comment]
Thanks! Should be fixed now. Reopen if it doesn't work for you.

**Comment by ireyon** [comment]
Yep, works now.
