### ISSUE TITLE
Great work! But I can't understand something

### ISSUE THREAD

**Issue by dial-up** [kobalicek/asmjit#109]
Several times I read the instructions, but I can not understand how to work in X64 mode. With I X86 had no problems. Everything works just fine. However, where are the classes X64Compiler, X64GpVar...?? I apologize for my stupid question and would be very grateful if you answer me.

**Comment by kirbyfan64** [comment]
@dial-up The X86 classes use 64-bit registers and such when on 64-bit platforms.

**Comment by kobalicek** [comment]
There is no such concept to make a difference between 32-bit and 64-bit anymore.

X86Assembler and X86Compiler both can generate code for x86 and x64 architectures. When using X86Assembler you need to take care of registers yourself, so you can use `asmjit::x86::regs` directly or architecture dependent  registers accessible through the code generator itself - `X86Assembler.zax` would result in `eax` or `rax` depending on the architecture.

Asmjit can also generate 64-bit assembly when running on 32-bit and vice versa.

**Comment by dial-up** [comment]
Thanks!!!
