### ISSUE TITLE
How to generate 32-bit code from 64-bit process?

### ISSUE THREAD

**Issue by DarkoreXOR** [kobalicek/asmjit#111]
I make a library that executes code in another processes. I need to generate 32-bit code is generated in a 64-bit host.

с++ code:
a.mov(x86::ebx.r32(), 0x12345678);
a.mov(x86::dword_ptr(x86::ebx.r32()), x86::eax.r32());
a.ret();

generated code:

from 32 to 32:
BB 78 56 34 12    mov         ebx,12345678h
89 03                   mov         dword ptr [ebx],eax
C3                        ret

from 64 to 32:
BB 78 56 34 12       mov         ebx,12345678h
67 89 03                 mov         dword ptr [ebx],eax
C3                           ret

The second version (64 -> 32) has prefix 0x67 so it does not work correctly in the target process. How to do it?

I need something like this:

JitRuntime runtime;
X86Assembler a(&runtime);
a.use16();
a.mov(x86::ax, x86::bx);
a.use32();
a.mov(x86::ebx, x86::edx);
a.use64();
a.mov(x86::rax, x86::rsp);
...

**Comment by kobalicek** [comment]
Use the second parameter of X86Assembler constructor to create a stream for a different architecture:

```
X86Assembler a32(&runtime, asmjit::kArchX86);
X86Assembler a64(&runtime, asmjit::kArchX64);
```

NOTE 1: Architecture is specified at construction time, I don't know what would happen if you call `a.setArch(kArch...)` on the instance that already contains something, maybe some fixes will be necessary to make that possible.

NOTE 2: AsmJit by default builds just the architecture for JIT code generation, specify `ASMJIT_BUILD_X86` and `ASMJIT_BUILD_X64` to support both architectures.

**Comment by kobalicek** [comment]
Closing, reopen if you have any problems with it.
