### ISSUE TITLE
CMake header paths

### ISSUE THREAD

**Issue by saeschdivara** [kobalicek/asmjit#112]
I am not sure if this problem should be handled by the cmake file but when I tried to compile asmjit I got an regex error because in my path was a C++ directory.

A fix may be something like that:

    String(REPLACE "++" "\\+\\+" ASMJIT_SRC_DIR_ESCAPED ${ASMJIT_SRC_DIR})
    String(REGEX REPLACE "^${ASMJIT_SRC_DIR_ESCAPED}/" "" targetpath "${path}")

**Comment by kobalicek** [comment]
I really hope this is a cmake issue and cmake projects don't have to contain such hacks. Is there any relevant info about this?

**Comment by kobalicek** [comment]
You didn't have to close :) I just wonder if this is a known problem of cmake or responsibility of asmjit to handle these characters properly.

**Comment by saeschdivara** [comment]
Well I am not sure either, I just wanted to have a solution for others which would have this problem

**Comment by kirbyfan64** [comment]
There doesn't seem to be any kind of alternative. At all. One option could be to slice it. Something like (UNTESTED):

```cmake
String(FIND "${path}" "${ASMJIT_SRC_DIR}/" pos)
If(${pos} EQUAL 0)
    String(SUBSTRING "${path}" "${pos}" -1 targetpath)
Else()
    # Substring was not found at beginning of ${path}
    Set(targetpath "${path}")
Endif()
```

Hey, I had offered to use something other than CMake before... ;)
