### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by saeschdivara** [kobalicek/asmjit#113]
I wanted to ask if it would be possible to add a breakpoint to the jit runtime instructions and maybe add a callback so one could analyse the current function for example.

**Comment by kirbyfan64** [comment]
I don't think this is possible right now at all. What you *can* do is this:

```c++
JitRuntime runtime;
X86Compiler c(&runtime);
// this is the cool part!
FileLogger logger(stdout);
c.setLogger(&logger);
// ...
```

That will cause the generated assembly to be printed to the screen. Same thing for the `X86Assembler` class.

**Comment by kobalicek** [comment]
There is also `int3` instruction that can trigger a breakpoint, basically the same as `__debugbreak()`.
