### ISSUE TITLE
Error C4703: potentially uninitialized local pointer variable 'varMapping' used

### ISSUE THREAD

**Issue by mohamadnorouzi20** [kobalicek/asmjit#114]
I'm using visual studio 2015 and after building your first example this error occured
in "asmjit\x86\x86compiler.cpp" line:349

**Comment by kobalicek** [comment]
There is a pull for this already: https://github.com/kobalicek/asmjit/pull/108

**Comment by kobalicek** [comment]
Closed by https://github.com/kobalicek/asmjit/commit/6758955e8c0e7d74fc65c2736a4d007e09f770ca
