### ISSUE TITLE
Do you know of any asmjit-based expression evaluator that is up to date with the current asmjit?

### ISSUE THREAD

**Issue by nelson2005** [kobalicek/asmjit#115]
preferably a double-based one.

**Comment by kobalicek** [comment]
There was a doublepresso project (fork of mathpresso), but I have no clue about its status. I started a new one called MPSL, but it's not functional at the moment and it's more-like a shader (it has types, branches, and loops), but, it has a much better architecture and I intend to use it in Blend2D library.

However, I didn't really work on it past months as I work on Blend2D most of my time now, maybe I can take a look and check if I can hack it to be functional even if not super-optimized.

**Comment by kobalicek** [comment]
I will also check-out the doublepresso, maybe it's just few changes to make it working again.

**Comment by nelson2005** [comment]
I took a look at the doublepresso code and talked to tartakynov, it seems like he might be picking it up again sometime in the near future.  I've been watching for MPSL.  Anyway, no worries, I was just hoping you knew of some MPSL-like project that was ready to up to date.

**Comment by kobalicek** [comment]
I'm gonna reserve this weekend to finalize asmjit's next branch. Then I can take a look and try to port mathpresso to the new asmjit or try to make MPSL working (would be better, but no idea if I can hack it over the weekend). Not promising anything thought.

**Comment by kobalicek** [comment]
and btw yeah, using floats in mathpresso was a stupid idea :)

**Comment by kobalicek** [comment]
Let's keep this open for a while.

**Comment by nelson2005** [comment]
That would be great!  I don't know assembly language, but I'd be happy to make a contribution to the food and beverage fund.
On Dec 4, 2015 7:42 PM, Petr Kobalicek <notifications@github.com> wrote:I'm gonna reserve this weekend to finalize asmjit's next branch. Then I can take a look and try to port mathpresso to the new asmjit or try to make MPSL working (would be better, but no idea if I can hack it over the weekend). Not promising anything thought.

**Comment by kobalicek** [comment]
Erik, I have hacked mathpresso to work with the newest asmjit, I refactored it a bit and I'm planning to make it available soon. 

Let me know if you need it ASAP.

**Comment by nelson2005** [comment]
Wow, that's great!  I'll start playing with it tomorrow if it's posted somewhere.  If not, I'll pick it up when you do make it available.
Thanks
Erik
On Dec 6, 2015 6:09 PM, Petr Kobalicek <notifications@github.com> wrote:Erik, I have hacked mathpresso to work with the newest asmjit, I refactored it a bit and I'm planning to make it available soon. 

Let me know if you need it ASAP.

**Comment by kobalicek** [comment]
It's available here:

https://github.com/kobalicek/mathpresso-ng

It's not completely up to date with DoublePresso fork, will update soon.

**Comment by nelson2005** [comment]
Thanks, I downloaded a copy and am trying it out now.

**Comment by kobalicek** [comment]
I'm closing this, thanks for experimenting with mathpresso-ng :)
