### ISSUE TITLE
mov eax,[ecx+0CC]

### ISSUE THREAD

**Issue by paralin** [kobalicek/asmjit#118]
I can't for the life of me find the x86 asmjit equivalent to `mov eax,[ecx+0CC]`.

This is close: `c.mov_ptr(x86::eax, x86::ptr(x86::ecx, 0x0CC));` but the arguments are wrong.

Any ideas?

**Comment by kobalicek** [comment]
This should work:

```
assembler.mov(x86::eax, x86::ptr(x86::ecx, 0xCC));
```

**Comment by paralin** [comment]
Thanks, just using the assembler works.
