### ISSUE TITLE
X86Assembler::align() returns kErrorInvalidArgument when trying to create a single byte constant with newByteConst/newConst

### ISSUE THREAD

**Issue by gunnarbeutner** [kobalicek/asmjit#127]
Example Code (CStr() returns 1):

	String str = value;

	asmjit::X86Mem val = compiler.newConst(asmjit::kConstScopeLocal, str.CStr(), str.GetLength());

	asmjit::X86GpVar pval = compiler.newIntPtr("pval");
	compiler.lea(pval, val);

	call = compiler.addCall(asmjit::imm_ptr(&JitNewValueString), asmjit::FuncBuilder3<void, const char *, size_t, Value *>(asmjit::kCallConvHost));
	call->setArg(0, pval);
	call->setArg(1, asmjit::imm(str.GetLength()));
	call->setArg(2, res);`

This causes the check in x86assembler.cpp:411  to fail:

	asmjit.dll!asmjit::X86Assembler::align(unsigned int alignMode, unsigned int offset) Line 411	C++
 	asmjit.dll!asmjit::X86Context::serialize(asmjit::Assembler * assembler_, asmjit::HLNode * start, asmjit::HLNode * stop) Line 5679	C++
 	asmjit.dll!asmjit::X86Compiler::finalize() Line 293	C++

The offset argument for the align() call is 1:

     if (alignMode > kAlignZero || offset <= 1 || !Utils::isPowerOf2(offset) || offset > 64)

This problem does not occur when I create at least one other constant in the same scope, i.e. it only seems to occur when the entire constant pool's size is 1.

**Comment by kobalicek** [comment]
Thanks! The alignment check needs to be relaxed. I have never hit this before.

**Comment by kobalicek** [comment]
Fixed, thanks!
