### ISSUE TITLE
Using an alignment other than 4 for newStack() generates invalid code

### ISSUE THREAD

**Issue by gunnarbeutner** [kobalicek/asmjit#128]
Example Code:

	asmjit::X86Mem v1 = compiler.newStack(16, 8);
	asmjit::X86Mem v2 = compiler.newStack(16, 8);

	asmjit::X86GpVar pv1 = compiler.newIntPtr();
	compiler.lea(pv1, v1);

	asmjit::X86GpVar pv2 = compiler.newIntPtr();
	compiler.lea(pv2, v2);

Generated code:

    03900040  mov         ecx,esp  
    03900042  sub         esp,14h  
    03900045  and         esp,0FFFFFFF8h  
    03900048  mov         dword ptr [esp],ecx  
    0390004B  mov         eax,dword ptr [ecx+4]  
    0390004E  mov         dword ptr [esp+8],eax  
    03900052  mov         eax,dword ptr [ecx+8]  
    03900055  mov         dword ptr [esp+0Ch],eax  
    03900059  mov         eax,dword ptr [ecx+0Ch]  
    0390005C  mov         dword ptr [esp+10h],eax  
    03900060  lea         eax,[esp]  
    03900063  lea         eax,[esp]  
    03900066  mov         esp,dword ptr [esp]  
    03900069  ret

Note how both `lea` instructions load the same address.

**Comment by kobalicek** [comment]
I closed the wrong bug

**Comment by kobalicek** [comment]
Let me know if it works for you

**Comment by gunnarbeutner** [comment]
Seems to be working. Thanks. :)

**Comment by kobalicek** [comment]
Thank you for the bug report, appreciated :)
