### ISSUE TITLE
Move immediate into a byte?

### ISSUE THREAD

**Issue by tgharib** [kobalicek/asmjit#129]
Hi all,

I'm having some difficulty moving an immediate into a byte. I am only using the X86Assembler and not the X86Compiler because I want the instructions to be assembled at compile-time instead of adding overhead in runtime. I've tried the following: `assembler.mov(&InterrupterGlobals::interruptStatusCode, 2);` but I got this error: `/home/owner/Downloads/C8Emulator/src/production/dynamic_recompiler/Translator.cpp:18:62: error: no matching function for call to ‘asmjit::X86Assembler::mov(uint8_t*, int)’`

Is this simply not possible without using the X86Compiler?

**Comment by kobalicek** [comment]
It's possible, you need to use an absolute address:

```
using namespace asmjit;
void* yourPtr;
int someValue;
assembler.mov(x86::byte_ptr_abs(Ptr(yourPtr)), someValue);
```

But this will only work on 32-bit target, 64-bit absolute addressing is limited to addresses that only use 32 bits, you need a register in such case.

**Comment by tgharib** [comment]
Thank you! Makes sense. :)
