### ISSUE TITLE
bug with if-else

### ISSUE THREAD

**Issue by kirill-terekhov** [kobalicek/asmjit#3]
Test cases for testx86.cpp:

1. the following will work once you replace in X86X64Context::switchState

// Ignore if both states are equal.
  if (cur == src)
with
  if (cur == src || src == NULL)
I know this is the bad way, but it works.

struct X86Test_IfElseInt : public X86Test {
	X86Test_IfElseInt() : X86Test("[IfElse] If-else statement") {}

	static void add(PodVector<X86Test*>& tests) {
		tests.append(new X86Test_IfElseInt());
	}

	virtual void compile(Compiler& c) {
		c.addFunc(kFuncConvHost, FuncBuilder2<int,int,int>());

		
		GpVar v1(c,kVarTypeInt32);
		GpVar v2(c,kVarTypeInt32);
		Label l1(c), l2(c);

		c.setArg(0, v1);
		c.setArg(1, v2);

		c.cmp(v1, v2);
		c.jg(l1);
		c.mov(v1, imm(1));
		c.jmp(l2);
		c.bind(l1);
		c.mov(v1, imm(2));
		c.bind(l2);
		c.ret(v1);
		c.endFunc();
	}

	virtual bool run(void* _func, StringBuilder& result, StringBuilder& expect) 
	{
		typedef int(*Func)(int,int);
		Func func = asmjit_cast<Func>(_func);
		return (func(5,0) == 2) && (func(0,5) == 1);
	}
};

2. the following code will fail on analyze().
Commenting out removeUnreachableCode() in compile() helps a little, but then it fails anyway.

struct X86Test_IfElseInt2 : public X86Test {
	X86Test_IfElseInt2() : X86Test("[IfElse] If-else statement 2") {}

	static void add(PodVector<X86Test*>& tests) {
		tests.append(new X86Test_IfElseInt2());
	}

	virtual void compile(Compiler& c) {
		c.addFunc(kFuncConvHost, FuncBuilder2<int, int, int>());

		GpVar v1(c, kVarTypeInt32);
		GpVar v2(c, kVarTypeInt32);
		Label l1(c), l2(c), l3(c), l4(c);

		c.setArg(0, v1);
		c.setArg(1, v2);
		
		c.jmp(l1);
		c.bind(l2);
		c.jmp(l4);
		c.bind(l1);

		
		c.cmp(v1, v2);
		c.jg(l1);
		c.mov(v1, imm(1));
		c.jmp(l2);
		c.bind(l3);
		c.mov(v1, imm(2));
		c.jmp(l2);

		c.bind(l4);

		c.ret(v1);
		c.endFunc();
	}

	virtual bool run(void* _func, StringBuilder& result, StringBuilder& expect)
	{
		typedef int(*Func)(int, int);
		Func func = asmjit_cast<Func>(_func);
		return (func(2, 1) == 2) && (func(1, 2) == 1);
	}
};

There are some additional problems when comparing and working with floating-point values with Xmm variables. I have to do a redundant mov operation inside each if-else brench, otherwise it fails on assertion:
Assertion failed: vd->getState() == kVarStateReg, file x86context_p.h, line 254
probably because I modified code as in example 1.
I can't provide example for this compatible with testx86.cpp, because for x86 I don't know how to make movs between GpVar and XmmVar.

**Comment by kobalicek** [comment]
https://github.com/kobalicek/asmjit/commit/5f04cbb8ec01bc61bf3a21c1dae4b624e4b6c293

**Comment by kobalicek** [comment]
Floating point values returning in st0/st1 are now supported.
