### ISSUE TITLE
Assemble to preallocated memory

### ISSUE THREAD

**Issue by bnoordhuis** [kobalicek/asmjit#32]
Hi, feature request: I would like the assembler to have an option where it assembles directly to memory that I as the user have allocated.

My use case is a profiler that diverts return addresses on the stack to customized landing pads in rwx memory.  I'm putting the landing pads together by hand now but that's tedious and error prone so I would like to use asmjit for that.

I'll be happy to work on it.  I was thinking alloc/realloc/release callbacks but if there's a better approach, just let me know.

**Comment by kobalicek** [comment]
Guys is this fine now or still some tweaks needed? I would like to close this if everybody is happy :)

**Comment by bnoordhuis** [comment]
I haven't checked but I'm fine with closing it.  I can file a new issue if something pops up.

**Comment by kobalicek** [comment]
Thanks! Gonna close it, and thanks for your work on node/io !
