### ISSUE TITLE
*** ERROR: No virtual memory (2).

### ISSUE THREAD

**Issue by Nekotekina** [kobalicek/asmjit#38]
It often throws this error, but very little amount of code is generated. Also it throws assert in debug mode:

x86assembler.cpp: line 1935
ASMJIT_ASSERT(o0->getSize() == 1);

**Comment by kobalicek** [comment]
Hi Ivan, do you still have problems with this ? I would close otherwise.

**Comment by Nekotekina** [comment]
Hi, it never occured last time. I think it can be closed.

**Comment by kobalicek** [comment]
thanks, closing.
