### ISSUE TITLE
How to write portable code?

### ISSUE THREAD

**Issue by peastman** [kobalicek/asmjit#51]
I'm working on an application that needs to work on Linux, Mac, and Windows, both 32 and 64 bit.  That covers several different ABIs.  I'm trying to figure out how I can write my code in a way that will work on all of them.

I first wrote it on Mac and got everything working.  Then I tried it on 64 bit Linux and that worked fine.  But then I tried Windows (64 bit, but compiling a 32 bit executable) and it crashed.  Then I tried 32 bit Linux and it also failed.

I believe this is due to differences in ABIs.  For example, 64 bit platfoms use Xmm registers for floating point values, but most 32 bit platforms use Fp registers.  But AsmJit requires me to use a completely different type of variable depending on which one is going to be used.  As far as I can tell, there's no way to tell it, "This is a floating point variable.  Use whatever type of register is appropriate."

How can I write my code in a way that will work on all platforms?

**Comment by kobalicek** [comment]
Peastman: Returning is now supported, I'm closing this for now as there is currently nothing to fix.

**Comment by peastman** [comment]
That's great news!  I'll give it a try.

**Comment by peastman** [comment]
Using the latest version of asmjit from the repository and compiling in 32 bit mode, my program crashes when I try to execute the compiled code.  If I compile in 64 bit mode it still works fine.

Is identical code supposed to work in both modes?  Or do I need to do something differently in 32 bit mode?

**Comment by kobalicek** [comment]
It should work the same, it's a bug if it doesn't.

I have just added this feature recently so it's possible it's still buggy, if you have any code that crashes fill a new issue and I will try to fix it.
