### ISSUE TITLE
AVX codegen

### ISSUE THREAD

**Issue by henrygouk** [kobalicek/asmjit#59]
I'm having problem using AVX instructions. When I try to make a simple program that just adds two vectors together using AVX instructions I get the incorrect result.

When I add in a breakpoint using a.db(0xCC) and use GDB to disassemble the machine code around the PC it looks like the code has not been generated properly.

Here is a gist with the program https://gist.github.com/henrygouk/44120a19d2ab3f51b010

And here is what I have gotten out of GDB:

    (gdb) disassemble $pc-17,+18
    Dump of assembler code from 0x7ffff7fe8000 to 0x7ffff7fe8012:
       0x00007ffff7fe8000:	vmovups (%rsi),%ymm0
       0x00007ffff7fe8004:	vmovups (%rdx),%ymm1
       0x00007ffff7fe8008:	vaddps %ymm1,%ymm1,%ymm0
       0x00007ffff7fe800c:	vmovups %xmm0,(%rdi)
       0x00007ffff7fe8010:	int3   
    => 0x00007ffff7fe8011:	retq   
    End of assembler dump.

the vaddps instruction has the wrong operands and the final vmovups instruction is operating on xmm0 instead of ymm0.

Am I doing something wrong, or is this a problem in asmjit?

**Comment by kobalicek** [comment]
Closing, should be fixed.
