### ISSUE TITLE
fstsw and fnstsw generate wrong opcode

### ISSUE THREAD

**Issue by Zeex** [kobalicek/asmjit#68]
When using the `fstsw ax` and `fntstsw ax` instructions asmjit outputs only part of their opcode. E.g. for `fnstsw ax` instead of `DF E0` it generates `E0`, which is `loopne`.

I used this program to reproduce the bug:

```c++
#include <asmjit/asmjit.h>

using namespace asmjit;
using namespace asmjit::x86;

int main() {
  JitRuntime runtime;
  X86Assembler a(&runtime);

  a.fnstsw(ax);
  void *code = a.make();

  runtime.release(code);
}
```

**Comment by kobalicek** [comment]
Thanks! Should be fixed.
