### ISSUE TITLE
It's impossible to generate jumps to arbitrary positions

### ISSUE THREAD

**Issue by LemonBoy** [kobalicek/asmjit#7]
As stated in the title, it's impossible at the moment to make asmjit generate a jump opcode pointing to something different than a label.
The pushf / ret combo is just an hack, the 0xE9 + offset way should be used instead.

**Comment by kobalicek** [comment]
I referenced this prematurely, had to reset the commit as it had some issues.

**Comment by kobalicek** [comment]
Worked on this a bit and added such possibility. However, I'm not sure about the use cases yet, but it's possible to just jump anywhere you want, and asmjit should properly do liveness analysis and register allocation in such case.

**Comment by kobalicek** [comment]
Closing
