### ISSUE TITLE
AsmJit crashes with functions with char argument

### ISSUE THREAD

**Issue by kirbyfan64** [kobalicek/asmjit#70]
Sample:

```c++
#include <asmjit/asmjit.h>

using namespace asmjit;
using namespace asmjit::x86;

int main() {
    JitRuntime runtime;
    X86Compiler c{&runtime};
    c.addFunc(kFuncConvHost, FuncBuilder1<int, char>{});

    // removing the next two lines makes no difference
    X86GpVar x{c, kVarTypeInt8, "x"};
    c.setArg(0, x);

    c.endFunc();
    c.make();
    return 0;
}
```

Output:

```
Assertion failed: aType < kX86VarTypeCount
, file src/asmjit/x86/x86compiler.cpp, line 145
Aborted (core dumped)
```

In release mode, it segfaults. It doesn't matter what I put in between. If I change the `char` argument to an `int`, it works perfectly.

**Comment by kobalicek** [comment]
Just checked it out, it should be `FuncBuilder1<int, char>()`, not `FuncBuilder1<int, char>{}`, can you verify?

**Comment by kirbyfan64** [comment]
Doesn't work for me. I built it with Clang SVN in C++11 mode.

**Comment by kobalicek** [comment]
Ok, I can reproduce in 32-bit mode

**Comment by kobalicek** [comment]
Should be fixed, can you check it out?

**Comment by kobalicek** [comment]
https://github.com/kobalicek/asmjit/commit/de444b874a606c7d4e7607dc7708e98ec03e1780

**Comment by kirbyfan64** [comment]
It works! Thanks!
