### ISSUE TITLE
xgetbv instruction not supported by the Mac OS X assembler

### ISSUE THREAD

**Issue by kulp** [kobalicek/asmjit#78]
Since 515d854d10e656fe410663d77400bf6ab5627541, the `xgetbv` instruction can be emitted in `src/asmjit/x86/x86cpuinfo.cpp` if the GCC version greater than or equal to 4.4. This is not a sufficient condition to permit compilation on Mac OS X, so it is not possible to do a straightforward compilation :

    $ c++ --version
    c++ (MacPorts gcc48 4.8.4_0) 4.8.4
    Copyright (C) 2013 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    
    $ c++ -DASMJIT_STATIC -I3rdparty/asmjit/src example_from_README.cxx $(find 3rdparty/asmjit/src/asmjit/{base,x86} -name \*.cpp)
    3rdparty/asmjit/src/asmjit/x86/x86cpuinfo.cpp:171:no such instruction: `xgetbv'

Trivially changing `callXGetBV()` to use the explicitly-encoded form `.byte 0x0F, 0x01, 0xd0` works.

I am not sure how to detect the assembler or Mac OS X environment reliably. The only preprocessor directives I see on a cursory glance that might work would be `__ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__` and `__MACH__`.

**Comment by kobalicek** [comment]
So basically it can be fixed by banning the name form on OSX? I have no problem with that, will commit tonight.

**Comment by kirbyfan64** [comment]
FYI, libyuv just unconditionally [uses the explicit byte form](http://code.google.com/p/libyuv/source/browse/trunk/source/cpu_id.cc#111).

**Comment by kobalicek** [comment]
Thanks guys, following the byte form as well.
