### ISSUE TITLE
Add an overload of the Imm constructor for pointers (mostly `void*`)

### ISSUE THREAD

**Issue by kirbyfan64** [kobalicek/asmjit#80]
Right now, I have to do stuff like this:

```c++
void* ptr = xyz;
c.mov(var, static_cast<intptr_t>(xyz));
```

It would be great if the `Imm` constructor could also take a `void*` pointer.

**Comment by kobalicek** [comment]
It should be possible to just write `imm_ptr(xyz)`, does it work for you?

**Comment by kirbyfan64** [comment]
It works...but it still sucks that I have to `static_cast` everything to `void*`.

Could an overload be added like this?

```c++
template <typename T>
static ASMJIT_INLINE Imm imm_ptr(T* p) { return imm_ptr(reinterpret_cast<void*>(p)); }
```

**Comment by kobalicek** [comment]
Yes, that's a good idea, but I thought that any pointer would implicitly cast to `void*` anyway.

**Comment by kirbyfan64** [comment]
@kobalicek That's only in C, unless your compiler isn't conformant.

**Comment by kobalicek** [comment]
It should be fixed by https://github.com/kobalicek/asmjit/commit/3d62c94c8efe5a06d432a7f07ffb477e03f0e923 . imm_ptr now is templated, should work for any case basically.

**Comment by kobalicek** [comment]
Closing.
