### ISSUE TITLE
Register names overlap with asmjit stuff in debugger

### ISSUE THREAD

**Issue by Nekotekina** [kobalicek/asmjit#82]
Maybe I'm really very stupid here...

![asmjit](https://cloud.githubusercontent.com/assets/6028184/7244430/eeed6a20-e7e3-11e4-97b2-80e983a21654.png)

When I use disasm in VS debugger, it displays this instead of register's content when mouseovered. Looks like VS bug though.

**Comment by kobalicek** [comment]
Yes this looks like a VS bug, not sure about the version you are using. But I have never faced this one.

**Comment by kobalicek** [comment]
I just don't know if this can be fixed at asmjit side, I think this should be reported to VS team.

**Comment by kobalicek** [comment]
I marked as invalid as this is not asmjit's bug, but I will keep open for others.

**Comment by kobalicek** [comment]
Closing, I cannot do anything here :(
