### ISSUE TITLE
Question: Calling external functions

### ISSUE THREAD

**Issue by saeschdivara** [kobalicek/asmjit#86]
Hi

I wanted to know if and how I can call external functions say from a library.
Say for example printf.

**Comment by kirbyfan64** [comment]
Something like:

```
X86GpVar ptr_puts(c, kVarTypeIntPtr, "puts");
c.mov(ptr_puts, puts);
// call puts("abc")
const char s[] = "%d\n";
c.call(ptr_puts, kFuncConvHost, FuncBuilder1<void, const char*>())->setArg(0, s);
```

I don't think AsmJit supports variadic functions, though... (if it does, please let me know!)

**Comment by kobalicek** [comment]
It doesn't, but I can fix that.

**Comment by kobalicek** [comment]
BTW: You can check asmjit x86 tests to see how calling an external function works, it uses `asmjit::Compiler` though, if you are just using `Assembler` class you have to do it yourself.

**Comment by saeschdivara** [comment]
Hey thanks for the answer.
I have a question to your anwser though.
In the line: c.mov(ptr_puts, puts);
is puts included from stdio.h ?

**Comment by kirbyfan64** [comment]
Yes.

**Comment by saeschdivara** [comment]
Well, I wonder if this code example compiles for you because it doesn't do for me.
c.mov(ptr_puts, puts);
cannot find a definition
and ->setArg(0, s)
doesn't work with a char pointer.

Can you please give me a compiling example?
Or what do I need to do that it compiles?

**Comment by kobalicek** [comment]
You can use `imm_ptr(puts)`, that would convert the function pointer into an immediate value

**Comment by saeschdivara** [comment]
Ok, that with the pointer worked but this still doesn't compile:
X86CallNode * node = c.call(ptr_puts, kFuncConvHost, FuncBuilder1<void, const char*>());
node->setArg(0, s); 

Compiler output:

../asmjit/src/asmjit/x86/x86compiler.h:1415:22: note: candidate function not viable: no known conversion from 'const char [4]' to 'const asmjit::Var' for 2nd argument
  ASMJIT_INLINE bool setArg(uint32_t i, const Var& var) { return _setArg(i, var); }
                     ^
../asmjit/src/asmjit/x86/x86compiler.h:1417:22: note: candidate function not viable: no known conversion from 'const char [4]' to 'const asmjit::X86FpReg' for 2nd argument
  ASMJIT_INLINE bool setArg(uint32_t i, const X86FpReg& reg) { return _setArg(i, reg); }
                     ^
../asmjit/src/asmjit/x86/x86compiler.h:1419:22: note: candidate function not viable: no known conversion from 'const char [4]' to 'const asmjit::Imm' for 2nd argument
  ASMJIT_INLINE bool setArg(uint32_t i, const Imm& imm) { return _setArg(i, imm); }

**Comment by kobalicek** [comment]
Let's try `node->setArg(0, imm_ptr(s))`

**Comment by saeschdivara** [comment]
Hey, cool, it worked :+1: 

Here is my final code:

```c++
X86GpVar ptr_puts(c, kVarTypeIntPtr, "printf");
c.mov(ptr_puts, imm_ptr(printf));
// call puts("abc")
const char s[] = "%s | %s\n";
const char s2[] = "foo me bar";
const char s3[] = " kkk";
X86CallNode * node = c.call(ptr_puts, kFuncConvHost, FuncBuilder3<void, const char*, const char*, const char*>());
node->setArg(0, imm_ptr(s));
node->setArg(1, imm_ptr(s2));
node->setArg(2, imm_ptr(s3));
```

**Comment by kobalicek** [comment]
Unfortunately this is gonna fail in 64-bit mode since asmjit doesn't support variadic functions.

**Comment by kobalicek** [comment]
I created a ticket https://github.com/kobalicek/asmjit/issues/88 for it, and closing this one

**Comment by saeschdivara** [comment]
What do you mean with 64-bit mode?
I have a 64-bit compiler as far as I know. So how can I know that it won't work?

**Comment by kobalicek** [comment]
Calling variadic functions is not supported atm - the calling convention is not compatible. I mean function like `int printf(const char* fmt, ...)` is not the same as `int printf(const char* fmt, char* a, char* b)` when called with 3 `char*` arguments.

**Comment by saeschdivara** [comment]
Well it works in my program. I mean it literally prints out the correct string.
What does that mean?
Does it mean that you cannot call variadic but you can call a variadic function with normal arguments and it works?

**Comment by sakjain92** [comment]
Has imm_ptr() been removed?

```
 error: no member named 'imm_ptr' in namespace 'asmjit'
    a.call(asmjit::imm_ptr(puts));
```

**Comment by kobalicek** [comment]
> Has imm_ptr() been removed?

Yes, use `imm()` instead - it's now a template function. In most cases you wouldn't even need to use it, but with pointers I guess you would.

> what's the best way to generate a call to a hardcoded address without the overhead of first storing the address in a register?

Use `call/jmp [mem]`. There is no absolute call in the ISA, so the assembler has to translate the address to a relative displacement, if the displacement is out of range it uses address-table section and patches the instruction to use memory operand.
