### ISSUE TITLE
Question: Creating structs

### ISSUE THREAD

**Issue by saeschdivara** [kobalicek/asmjit#87]
Hi

I wanted to ask if it is possible to generate structs as in c.

**Comment by kirbyfan64** [comment]
I usually allocate the [stack space for it](https://github.com/kobalicek/asmjit/blob/master/README.md#using-stack). It'd likely be something like (UNTESTED)

```c++
struct Struct { int a, b; }
// allocate memory for a struct
X86Mem mystruct = c.newStack(sizeof(Struct), 4);
// set a to 4
c.mov(mystruct.clone().setIndex(offsetof(Struct, a)).setSize(sizeof(int)), 4);
// set b to 5
c.mov(mystruct.clone().setIndex(offsetof(Struct, b)).setSize(sizeof(int)), 5);
// return a
c.ret(mystruct.clone().setIndex(offsetof(Struct, a)).setSize(sizeof(int)));
```

**Comment by kobalicek** [comment]
Hi there is also `ASMJIT_OFFSET_OF` that can be used to get a relative offset of a C/C++ struct.

**Comment by kirbyfan64** [comment]
What's the difference between that and `offsetof`?

**Comment by kobalicek** [comment]
But there is no concept of `struct` in asmjit, struct is just a layout of some memory that you can have pointer to, or you can create on the stack. So basically it's up to you.

**Comment by kobalicek** [comment]
There is basically no difference of `offsetof` is available and provided by your compiler. I guess there is no `offsetof` if you use MSVC.

**Comment by kobalicek** [comment]
It's available also under MSVC so you can just use that, according to your preference

**Comment by saeschdivara** [comment]
What if I wanted to allocate an instance of a struct on the heap?
Would I have to call the external function malloc to do that?

**Comment by saeschdivara** [comment]
So in generell for the c++ types: array, struct, class, union I need to do it this way?
And what if I wanted to do this all generic say for some jit compiler I wanted to write?

**Comment by kirbyfan64** [comment]
1. Yes.

2. The thing about JITs is that they are never fully platform-agnostic. You need to know how the compiler represents internal values.

For instance, an n-element array of type T can be created by allocating `n*sizeof(T)` bytes of stack space.

A union is actually the size of its largest member. Take this union:

```c++
union X {
    int a, b; char c; long d;
}
```

`d` is the largest element (it takes the most space: 8 bytes on an x64 system). Therefore, whenever we do this:

```c++
X mything;
mything.c = 0;
```

it's actually the same thing as this:

```c++
long mything;
*((char*)&mything) = 0;
```

**Comment by saeschdivara** [comment]
And if I recall it correctly classes are nothing but structs with function pointers, right?
Function pointers are not any different from any pointer, correct?

**Comment by kobalicek** [comment]
There is basically no different between `struct` and `class` in C++, except that `class` starts with `private` scope.

Thinks change when you start adding virtual functions to your classes, in that case C++ compiler creates a virtual function table, which is usually the first _invisible_ member of the class. It's tricky to access these in JIT, it's not impossible, but I would say it's not really worth it to start messing with it.

In addition, there is also a huge difference between function pointers and member function pointers. This article probably explains the concept well, even if it's related to delegates: 

http://www.codeproject.com/Articles/7150/Member-Function-Pointers-and-the-Fastest-Possible

**Comment by saeschdivara** [comment]
Hey thanks for your answer and article. I will take a look at the article

**Comment by kobalicek** [comment]
BTW: To answer your memory related questions:

Allocating on the heap works the same way you do in C/C++ - use `malloc()`. VMs usually have a concept of isolation - they create a large heap that is used for all allocations and where GC tasks are performed. In that case you don't call `malloc()`, but you use your own allocator that uses the memory owned by the isolate. If you are creating a real VM, then I think you will have to work a bit more on these concepts as your data will probably live in the same heap as your code. This means that you will want to generate something like position independent code that can be moved in memory - I'm not sure if anyone did this with asmjit, I would say no.
