### ISSUE TITLE
Is there a way to print the generated assembly ?

### ISSUE THREAD

**Issue by ssarangi** [kobalicek/asmjit#89]
I didn't see it in any of the examples or docs so I was wondering if there was support for printing the generated assembly ?

**Comment by kirbyfan64** [comment]
AsmJit's docs mention the [loggers](https://github.com/kobalicek/asmjit/blob/master/README.md#logging-and-error-handling), which is probably what you want. Example:

```c++
FileLogger logger(stdout);
my_compiler.setLogger(&logger);
// now the generated assembly will be printed
```

The fact I know so much about this library is kind of weird...

**Comment by ssarangi** [comment]
Thanks a lot... I didn't realize the loggers were doing this. I thought they were for only logging errors.
Thanks :)

**Comment by kobalicek** [comment]
kirby: or it means the library is so easy to use :-) ?

**Comment by kirbyfan64** [comment]
Or I just have too much free time. ;)

**Comment by ssarangi** [comment]
well i agree... definitely very well written... :) The abstraction of the compiler & assembler is really good to experiment with.
