### ISSUE TITLE
Threading

### ISSUE THREAD

**Issue by saeschdivara** [kobalicek/asmjit#90]
Hello

I wanted to ask for one is the jit compiler thread safe?
My other question is can I start with my jit compiled code new threads
and run some functions there?

**Comment by kobalicek** [comment]
Hi,

it's not really stated in documentation, but yes. The Runtime is thread-safe and Assembler/Compiler  are reentrant - you cannot use the same instance of these from multiple threads, but you can create as many instances you need in two or more threads.

Hope it answers the question.

**Comment by saeschdivara** [comment]
So do I understand it correctly that the Assembler/Compiler create the instructions and the Runtime executes them in the current thread?
Which would mean that I handle all threading in my application without jit but give jit the chance to start threads via some function from me?

**Comment by kobalicek** [comment]
AsmJit never runs the generated code. Assembler/Compiler are used to generate the code stream, and Runtime is used to provide a memory where the code will be stored and relocated (you can use your own runtime if you just inherit from `BaseRuntime`).

I still don't know if you want to create threads from JIT code or use JIT code from threads you created before. You can do both, but I would just create threads outside of JIT and use them to run JIT code.

**Comment by saeschdivara** [comment]
Well, with my questions I wanted to determine which was possible and which one you would  recommend.
So I probably do as you said and try to run it from the outside.

**Comment by kobalicek** [comment]
Yeah, I think it's just simpler to create threads from outside instead of calling the APIs to create them from a generated code, but it really depends on what you are trying to do :)

**Comment by saeschdivara** [comment]
Well I try to create a jit compiler / vm for a language I am starting to create.
In which I want to make it easy to do threading
