### ISSUE TITLE
Creating a call to a function with return type kVarTypeFp32/64 crashes under x86_64

### ISSUE THREAD

**Issue by tcpie** [kobalicek/asmjit#91]
I would like to be able to call functions that return floating point values. Unfortunately, my program crashes when I call X86Compiler::make(). I am compiling for the x86_64 architecture, on Windows 7.

If I'm going about this the wrong way, do let me know as well :). 

Code to reproduce this issue:
```C++
void Crash(asmjit::JitRuntime* runtime, void* callback)
{
    X86Compiler c(runtime);

    VarType ret_type = kVarTypeFp64;

    // Build up the function definition
    FuncBuilderX fn_builder_x;

    fn_builder_x.setRet(kVarTypeInt32);

    c.addFunc(kFuncConvHost, fn_builder_x);

    FuncBuilderX callback_fn_builder;
    callback_fn_builder.setRet(ret_type);

    X86CallNode* call_node = c.call((Ptr)callback, kFuncConvHost, callback_fn_builder);

    X86GpVar return_value(c, ret_type, "return_value");

    call_node->setRet(0, return_value);

    c.ret(return_value);

    c.endFunc();

    void* fn = c.make(); // Program will crash here if ret_type is kVarTypeFp64 or 32
}
```

**Comment by kobalicek** [comment]
I'm travelling atm, but the code looks correct to me. I would first start to use templated function builder and if that passes it's bug in FuncBuilderX. I will check when I arrive.

**Comment by kobalicek** [comment]
I will check this today, sorry for delay, I didn't have chance to look at it last week.

**Comment by kobalicek** [comment]
Sorry for delay.

I checked the code and I can reproduce it, however, it fails an assertion. The code is problematic as it requires an implicit conversion of double to int, which is not really supported by asmjit atm.

**Comment by kobalicek** [comment]
Closing, this is not really a bug.
