### ISSUE TITLE
X86Compiler::endFunc() crashes when X86Compiler::addFunc() has not been called

### ISSUE THREAD

**Issue by tcpie** [kobalicek/asmjit#92]
It appears that when X86Compiler::endFunc() is called, without X86Compiler::addFunc() being called prior, the program crashes. Though of course it is silly to do something like this, I think it would be nice to gracefully return an error, instead of crashing (or was I meant to catch an exception? I'm not sure.)

I understand this probably is not a high-impact issue, but wanted to mention it nevertheless. I really appreciate the effort put into this project!

**Comment by kirbyfan64** [comment]
Other things that will make AsmJit crash include:

- Defining a label twice
- Forgetting to define a label

Usuall,  if you build in debug mode, there will be various assertions placed

**Comment by kobalicek** [comment]
But all of these cases are `ASSERT`ed, or not ?

**Comment by kirbyfan64** [comment]
@kobalicek Not in release mode (not that that's a bad thing).

**Comment by kobalicek** [comment]
Yeah, but that's the question, should asmjit catch errors in release mode that are really that much severe?

**Comment by kirbyfan64** [comment]
@kobalicek IMO, it shouldn't: these errors usually just come up during initial development/testing, when the user should already be using a debug build of AsmJit.

**Comment by kobalicek** [comment]
I'm closing this, keeping it as is for now.
