### ISSUE TITLE
AVX move instructions encoded wrong when using memory operand with shift

### ISSUE THREAD

**Issue by ireyon** [kobalicek/asmjit#95]
When using a memory operand with shift with AVX moves, AsmJit generates wrong binary.
In this case, it emits the ymm version of that particular instruction instead of xmm, but that seems to be rather coincidental.

```
[asmjit] vmovaps xmm2, [rsi+r10]             ; C4A178281416  // Correct
[asmjit] vmovaps xmm2, [rsi+r10*4]           ; C4A17C281496  // Should be C4A178281496
```

**Comment by kobalicek** [comment]
Thanks! Please check it out whether the issue is really fixed.
